// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NXgZrIyrVzK8mym9d5X4_9O5Js8XdjI',
    appId: '1:387068072829:web:f4863c5190786b95c1f214',
    messagingSenderId: '387068072829',
    projectId: 'parcialweb-7f80a',
    authDomain: 'parcialweb-7f80a.firebaseapp.com',
    storageBucket: 'parcialweb-7f80a.appspot.com',
    measurementId: 'G-CDQGLXM067',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKy1OlQcQJNEGf8h6ZXesEIIzxGO19GcY',
    appId: '1:387068072829:android:a91c8cdc76b2ad8fc1f214',
    messagingSenderId: '387068072829',
    projectId: 'parcialweb-7f80a',
    storageBucket: 'parcialweb-7f80a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtNwXYX9BKnO5mUSLHPzr8wzNimoSnTLM',
    appId: '1:387068072829:ios:4c2b8730e01a1422c1f214',
    messagingSenderId: '387068072829',
    projectId: 'parcialweb-7f80a',
    storageBucket: 'parcialweb-7f80a.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtNwXYX9BKnO5mUSLHPzr8wzNimoSnTLM',
    appId: '1:387068072829:ios:4c2b8730e01a1422c1f214',
    messagingSenderId: '387068072829',
    projectId: 'parcialweb-7f80a',
    storageBucket: 'parcialweb-7f80a.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7NXgZrIyrVzK8mym9d5X4_9O5Js8XdjI',
    appId: '1:387068072829:web:bb7654c7899f2c49c1f214',
    messagingSenderId: '387068072829',
    projectId: 'parcialweb-7f80a',
    authDomain: 'parcialweb-7f80a.firebaseapp.com',
    storageBucket: 'parcialweb-7f80a.appspot.com',
    measurementId: 'G-8VXNKS3Z83',
  );
}
